### ISSUE TITLE
脚本还更新吗

### ISSUE THREAD

**Issue by ci6o1u0** [Mas0nShi/CXW-SZJXY#2]
脚本还更新吗，配置好了之后报错

Traceback (most recent call last):
  File ".\cxw-szjxy.py", line 56, in <module>
    answers()
  File ".\cxw-szjxy.py", line 11, in answers
    task_list = list(get_task_lists())
  File "E:\CXW-SZJXY-master\cxw\modules\task.py", line 139, in get_task_lists
    tasks = _serialize_task_list(get_channel_id())
  File "E:\CXW-SZJXY-master\cxw\modules\location.py", line 10, in get_channel_id
    assert j['code'] == 0, 'Get channel id failed'
AssertionError: Get channel id failed

**Comment by Mas0nShi** [comment]
看起来并没有问题：

```yaml
[answer]
location = "杭州"
```

```shell
$ python3 cxw-szjxy/cxw/modules/location.py 
5d8c0f39ffebf500014a7713
```

如果可以，你可以在 File "E:\CXW-SZJXY-master\cxw\modules\location.py", line 10 前 print(j) 看看响应内容

**Comment by Mas0nShi** [comment]
后续看了一下，一些字段被修改了，需要更新。

不巧的是个人暂时没精力更新脚本 :(
